name: Build and Package with Nuitka

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Nuitka and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r requirements.txt

      - name: Compile with Nuitka
        run: |
          nuitka --standalone --onefile --output-dir=dist --output-filename=uw main.py 

      - name: Upload Compiled Binary
        uses: actions/upload-artifact@v4
        with:
          name: my-binary
          path: dist/uw  # Adjust path based on Nuitka output
