name: Manual Build and Release with Nuitka

on:
  workflow_dispatch:

permissions:
  contents: write  # Required to create tags and releases

jobs:
  build-release:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Nuitka and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r requirements.txt

      - name: Compile with Nuitka
        run: |
          nuitka --standalone --onefile --output-dir=dist --output-filename=uw main.py 

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo v0.0.0)
          echo "CURRENT_TAG=$TAG" >> $GITHUB_ENV

      - name: Bump version and create new tag
        run: |
          OLD_TAG=${{ env.CURRENT_TAG }}
          VERSION=$(echo $OLD_TAG | awk -F. -v OFS=. '{$NF += 1 ; print}')
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag $VERSION
          git push origin $VERSION
          echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_VERSION }}
          files: dist/uw
